---
- hosts: all
  remote_user: ansible-exec
  become: yes
  tasks: 
  - name: install Apache
    yum:
      name: httpd
      state: latest
  - name: place custom homepage
    unarchive:
      src: index.tar
      dest: /var/www/html/
      group: apache
      owner: apache
  - name: open firewall for http
    firewalld:
      service: http
      permanent: true
      state: enabled
      zone: public
  - name: open firewall for https
    firewalld:
      service: https
      permanent: true
      state: enabled
      zone: public
  - name: restart firewalld 
    service:
      name: firewalld
      state: reloaded
  - name: enable and start httpd service
    service:
      name: httpd
      state: started
      enabled: yes


