---
- hosts: all
  remote_user: ansible-exec
  become: yes
  vars_files:
  - vars/private-idm.yml
  vars_prompt:
  - name: ipaserver_admin_password
    prompt: 'What should the admin password be for IPA? '
    private: yes
    default: 'tahder1!'
  - name: ipaserver_dir_admin_password
    prompt: 'What should the admin password be for the Directory Server? '
    private: yes
    default: 'tahder1!'
  tasks: 
  - name: install ipa-server
    yum:
      name: ipa-server
      state: latest
  - name: install ipa-server-dns
    yum: 
      name: ipa-server-dns
      state: latest
  roles:
  - { role: gregswift.ipaserver }

