---
- name: test
  hosts: localhost
  gather_facts: false
  vars:
   string1: "aa.bb.cc.dd"
   string2: "{{ input }}"
   upstring: "{{ string2|upper }}"
  tasks:
  - name: split 1
    debug: var=string1.split('.')
  - name: split 2
    debug: var=string2.split('.')[0]
  - name: split 2 upper
    debug: var=upstring.split('.')[0]


