---
- hosts: all
  remote_user: administrator
  vars:
    my_domain: winad.rhtxus.com
  tasks: 
  - name: create new WinAD Domain
    win_domain:
      dns_domain_name: '{{ my_domain }}'
      safe_mode_password: 'RedHat1!'
    register: domain_result
  - name: reboot if necessary
    win_reboot: 
    when: domain_result.reboot_required

