---
- hosts: all
  remote_user: ansible-exec
  become: yes
  tasks: 
  - name: register with Red Hat Subscription Management or Satellite
    redhat_subscription:
      activationkey: RHEL7
      org_id: antler
      state: present
  - name: install the katello-agent
    yum:
      name: katello-agent
      state: latest

