---
- hosts: all
  remote_user: ansible-exec
  become: yes
  tasks: 
  - name: install the katello CA
    yum:
      name: 'http://vrsat6.antler.rhtxus.com/pub/katello-ca-consumer-latest.noarch.rpm'
      state: present
  
