---
- hosts: all
  remote_user: ansible-exec
  become: yes
  tasks: 
  - name: create the repo file
    template:
      src: templates/local.repo.j2
      dest: /etc/yum.repos.d/local.repo
  - name: import the basic RPM-GPG key
    rpm_key:
      state: present
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  - name: run a yum update
    yum:
      name: '*'
      state: latest
  
