---
- hosts: localhost
#  ansible_connection: local
#  become: yes
  vars_prompt:
#    - name: "rhv_password"
#      prompt: "Enter RHV password"
    - name: "rhv_username"
      prompt: "Enter your RHV simple username without @profile"
      private: no
    - name: "rhv_vmname"
      prompt: "Enter a name for your VM"
      private: no
  tasks: 
    - name: get a RHV token
      ovirt_auth:
        username: "rhevadmin@antler.rhtxus.com"
        password: 'tahder1!'
        url: https://vrhvm1.antler.rhtxus.com/ovirt-engine/api
        insecure: true

    - name: create a VM
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        name: "{{ rhv_vmname }}"
        template: "{{ rhv_template_name }}"
        clone: True
        cluster: Trees
        state: '{{ my_state }}'
        stateless: False
      register: my_vm

    - name: enable permissions on new VM
      ovirt_permissions:
        auth: '{{ ovirt_auth }}'
        user_name: "{{ rhv_username }}"
        authz_name: antler.rhtxus.com-authz
        object_type: vm
        object_id: "{{ my_vm.id }}"
        role: UserVmManager

